BeginPackage["ISLR2`"];

AdDataset::usage = "A dataset for advertising data.";
AutoDataset::usage = "A dataset for auto data.";
BikeshareDataset::usage = "A dataset for bikeshare data.";
BostonDataset::usage = "A dataset for Boston housing data.";
BraincancerDataset::usage = "A dataset for brain cancer data.";
CaravanDataset::usage = "A dataset for caravan data.";
CarseatsDataset::usage = "A dataset for car seats data.";
CollegeDataset::usage = "A dataset for college data.";
Ch12ex13Dataset::usage = "A dataset for Ch12Ex13 data.";
CreditDataset::usage = "A dataset for credit data.";
DefaultDataset::usage = "A dataset for default data.";
FundDataset::usage = "A dataset for fund data.";
HeartDataset::usage = "A dataset for heart data.";
HittersDataset::usage = "A dataset for hitters data.";
Income1Dataset::usage = "A dataset for income1 data.";
Income2Dataset::usage = "A dataset for income2 data.";
KhanxtestDataset::usage = "A dataset for Khan_xtest data.";
KhanxtrainDataset::usage = "A dataset for Khan_xtrain data.";
KhanytestDataset::usage = "A dataset for Khan_ytest data.";
KhanytrainDataset::usage = "A dataset for Khan_ytrain data.";
NCI60Dataset::usage = "A dataset for NCI60 labs data.";
NYSEDataset::usage = "A dataset for NYSE data.";
OJDataset::usage = "A dataset for orange juice data.";
PortfolioDataset::usage = "A dataset for portfolio data.";
PublicationDataset::usage = "A dataset for publication data.";
SmarketDataset::usage = "A dataset for S&P market data.";
WageDataset::usage = "A dataset for wage data.";
WeeklyDataset::usage = "A dataset for weekly data.";

Begin["`Private`"]
AdDataset = Import["https://www.statlearning.com/s/Advertising.csv","Dataset","HeaderLines"->1];
AutoDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Auto.csv","Dataset","HeaderLines"->1];
BikeshareDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Bikeshare.csv","Dataset","HeaderLines"->1];
BostonDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Boston.csv","Dataset","HeaderLines"->1];
BraincancerDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/BrainCancer.csv","Dataset","HeaderLines"->1];
CaravanDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Caravan.csv","Dataset","HeaderLines"->1];
CarseatsDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Carseats.csv","Dataset","HeaderLines"->1];
CollegeDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/College.csv","Dataset","HeaderLines"->1];
Ch12ex13Dataset = Import["https://www.statlearning.com/s/Ch12Ex13.csv","Dataset","HeaderLines"->1];
CreditDataset = Import["https://www.statlearning.com/s/Credit.csv","Dataset","HeaderLines"->1];
DefaultDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Default.csv","Dataset","HeaderLines"->1];
FundDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Fund.csv","Dataset","HeaderLines"->1];
HeartDataset = Import["https://www.statlearning.com/s/Heart.csv","Dataset","HeaderLines"->1];
HittersDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Hitters.csv","Dataset","HeaderLines"->1];
Income1Dataset = Import["https://www.statlearning.com/s/Income1.csv","Dataset","HeaderLines"->1];
Income2Dataset = Import["https://www.statlearning.com/s/Income2.csv","Dataset","HeaderLines"->1];
KhanxtestDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Khan_xtest.csv","Dataset","HeaderLines"->1];
KhanxtrainDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Khan_xtrain.csv","Dataset","HeaderLines"->1];
KhanytestDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Khan_ytest.csv","Dataset","HeaderLines"->1];
KhanytrainDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Khan_ytrain.csv","Dataset","HeaderLines"->1];
NCI60Dataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/NCI60labs.csv","Dataset","HeaderLines"->1];
NYSEDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/NYSE.csv","Dataset","HeaderLines"->1];
OJDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/OJ.csv","Dataset","HeaderLines"->1];
PortfolioDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Portfolio.csv","Dataset","HeaderLines"->1];
PublicationDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Publication.csv","Dataset","HeaderLines"->1];
SmarketDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Smarket.csv","Dataset","HeaderLines"->1];
WageDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Wage.csv","Dataset","HeaderLines"->1];
WeeklyDataset = Import["https://raw.githubusercontent.com/intro-stat-learning/ISLP/main/ISLP/data/Weekly.csv","Dataset","HeaderLines"->1];
End[];
EndPackage[];
